name: beyond_flutter_cli
description: Flutter CLI tool for generating Clean Architecture project scaffolds and features
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  mason: ^0.1.0-dev.56
  path: ^1.8.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
