# Build configuration for build_runner
targets:
  $default:
    builders:
      freezed:
        options:
          # Generate files in freezed subdirectories
          build_extensions:
            "^lib/{{}}.dart": "lib/{{}}.freezed.dart"
        generate_for:
          - lib/**/*.dart
      json_serializable:
        options:
          # Generate files in freezed subdirectories
          build_extensions:
            "^lib/{{}}.dart": "lib/{{}}.g.dart"
        generate_for:
          - lib/**/*.dart