name: flutter_clean_architecture_app
description: A Flutter app built with Clean Architecture
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.8.1"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # HTTP Client
  dio: ^5.4.3+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Date/Time
  intl: ^0.19.0
  
  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  # Add assets here
  # assets:
  #   - images/
  #   - icons/
  
  # Add fonts here
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700